export const mapeoValores = {
    onapi: 13,
    certificadoVentas: 4,
    listaIngredientes: 14,
    descripcionElaboracion: 16,
    arteEtiqueta: 17,
    especificacionesEnvase: 15,
    permisoSanitario: 3,
    certificadoBuenasPracticas: 6,
    certificadoExportacion: 9,
    contratoFabricante: 8,
    poderRepresentante: 2,
    certificadoHabilitacion: 7,
    certificadoRegistroMercantil: 1,
    contratoAcondicionador: 9,
    muestra1: 18,
    muestra2: 18,
    muestra3: 18,
};